version: "3.9"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - tech_net

  app:
    container_name: tech
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9999:9999'
    environment:
      - POSTGRESQL_HOST=db
      - POSTGRESQL_PORT=${POSTGRESQL_PORT}
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - SERVER_PROTOCOL=${SERVER_PROTOCOL}
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_URL=${SERVER_URL}
      - DEV_MODE=${DEV_MODE}
    depends_on:
      - db
    networks:
      - tech_net

networks:
  tech_net:
    driver: bridge

volumes:
  db_data:
